Update auto-comment-pr-raise.yml
Signed-off-by: UTSAV SINGHAL <utsavsinghal26@gmail.com>

diff --git a/.github/workflows/auto-comment-pr-raise.yml b/.github/workflows/auto-comment-pr-raise.yml
--- a/.github/workflows/auto-comment-pr-raise.yml
+++ b/.github/workflows/auto-comment-pr-raise.yml
@@ -1,4 +1,4 @@
-name: Auto Comment on PR
+name: Auto Comment and Add Reviewer on PR
 
 on:
   pull_request_target:
@@ -9,7 +9,7 @@ permissions:
   pull-requests: write
 
 jobs:
-  comment:
+  comment-and-review:
     runs-on: ubuntu-latest
 
     steps:
@@ -30,6 +30,25 @@ jobs:
         cat response.json
         if [ "$RESPONSE" -ne 201 ]; then
           echo "Failed to add comment"
+          exit 1
+        fi
+    - name: Add Reviewer to Pull Request
+      run: |
+        REVIEWERS=$(cat <<EOF
+        {
+          "reviewers": ["UTSAVS26"]
+        }
+        EOF
+        )
+        RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
+          -X POST \
+          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+          -H "Accept: application/vnd.github.v3+json" \
+          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
+          -d "$REVIEWERS")
+        cat response.json
+        if [ "$RESPONSE" -ne 201 ]; then
+          echo "Failed to add reviewer"
           exit 1
         fi
       env:
